### ISSUE TITLE
abhinay auto night mode

### ISSUE THREAD

**Issue by bseditor** [imayushsaini/Bombsquad-modded-server-Mr.Smoothy#2]
plz help to fix the asscii error in your bsgame.py while using ubuntu 16.04 and following all the mentioned steps and not using abhinay server tools. below is the error

File "data/scripts/bsgame.py" line on 579
Syntax error: NON-ASCII character '/xe2' in the file data/scripts/bsgame.py line on 579, but no encoadings declared;

**Comment by S11720037** [comment]
![Screenshot at 2019-11-24 22-14-19](https://user-images.githubusercontent.com/50015208/69490558-ef562300-0ec4-11ea-9add-f3e485397423.png)
